name: PR Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Print head and base refs
      run: |
        echo "Head ref: ${{ github.head_ref }}"
        echo "Base ref: ${{ github.base_ref }}"

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Type check
      run: yarn typecheck
      continue-on-error: false

    - name: Check code quality
      run: |
        set -e
        trap 'echo "Error in $BASH_COMMAND at line $LINENO"' ERR
        yarn lint
        yarn format:check
        yarn run --if-present generate

    - name: Security Audit
      run: yarn audit --level moderate
      continue-on-error: true

    - name: Archive production artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./build/

    - name: Error handling
      if: ${{ failure() }}
      run: echo "CI failed. Please check the logs."
